name: 'Hello World Haohao.Xing action-a'
description: 'Greet aaaaaaaaaaaaaaa someone'
branding:
    icon: 'award'
    color: 'green'
inputs:
    who-to-greet:  # id of input
        description: 'Who to greet'
        required: true
        default: 'Worldaaaaaaaaaaaaaaaaaaaaaa'
runs:
    using: "composite"
    steps:
        - run: echo Hello ${{ inputs.who-to-greet }}.
          shell: bash
        - id: random-number-generator
          run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
          shell: bash
        - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
          shell: bash
        - run: action-a.sh
          shell: bash